### ISSUE TITLE
When the deck is completely depleted, can't draw faceup cards

### ISSUE THREAD

**Issue by jonah-henderson** [cs340tabyu/cs340Winter2018#244]
I might be reading things incorrectly, but if players keep drawing from the deck (i.e., not faceup) and draw all cards, they are unable to pick any of the remaining faceup cards. I assume they should be able to because there are still different colours available on the draw dialogue.

**Comment by jacobgb24** [comment]
The rules state "In the unlikely event that there are no cards left in the deck and there are no discards (because players are hoarding many cards in their hands), a player cannot draw Train
Car cards. Instead he may only claim a route or draw Destination Ticket cards." This is slightly ambiguous, but we interpret it to mean that if there are no cards in the deck a player must claim a route or draw dest cards. So the face up cards are still shown for the player's knowledge, but we will not allow them to take any until the deck has cards.
