### ISSUE TITLE
Order of Claim Routes

### ISSUE THREAD

**Issue by markwelker** [cs340tabyu/cs340Winter2018#253]
Order of train card colors in claim route selection changes frequently. Some kind of consistent ordering system would help so much, takes a while to find the right route.

**Comment by ephraimkunz** [comment]
I'm not sure how we'd fix this in a good way. We could sort the routes by title, but it creates a problem:
* Routes have an arbitrarily selected first and last city. So sorting by name doesn't make sense, because which name should you sort by?

In our current scheme, the relative ordering of all routes is consistent. Just some routes appear or disappear on each turn.
